### ISSUE TITLE
IsADirectoryError

### ISSUE THREAD

**Issue by rwols** [jsliang/sublime-pelican#36]
I get this exception in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in <lambda>
    run_callback('on_pre_save', callback, lambda: callback.on_pre_save(v))
  File "Pelican in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/Pelican.sublime-package", line 348, in on_pre_save
  File "Pelican in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/Pelican.sublime-package", line 390, in isPelicanArticle
  File "Pelican in /Users/rwols/Library/Application Support/Sublime Text 3/Installed Packages/Pelican.sublime-package", line 474, in parse_makefile
IsADirectoryError: [Errno 21] Is a directory: '/Users/rwols/Library/Application Support/Sublime Text 3/Packages/Makefile'
```
Please check if the file `Makefile` is actually a file before opening it.

**Comment by rwols** [comment]
ping @jsliang

**Comment by jsliang** [comment]
Hi @rwols ,

Sorry for the late reply. I haven't been using Sublime Text for like 2 years, and it has been quite difficult for me to keep up with the plugin maintenance ever since.

It would be great if you are willing to submit a PR for this issue. Thank you :)

jsliang
